services:
  api-server:
    container_name: api-server
    image: evanskj/book-shop:latest
    credentials:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
    ports:
      - 80: ${PORT}
    env_file:
      - /opt/elasticbeanstalk/deployment/env.list
