const ServiceMockData = {
  foundLocalUser: {
    email: 'test@test.com',
    id: 3,
    name: 'localUser',
    password: 'hashedPw',
    salt: 'someSalt',
    provider: 'LOCAL',
    provider_userId: null,
  },
  foundSnsUser: {
    email: 'test@social.com',
    id: 3,
    name: 'socialUser',
    password: 'hashedPw',
    salt: 'someSalt',
    provider: 'somethingSNS',
    provider_userId: 'somethingUserId',
  },
  bookDetailQueryResult: [
    {
      id: 2,
      title: '책',
      img: 5,
      form: '종이책',
      isbn: 5,
      summary: '요약',
      detail: '디테일',
      author: '작가',
      pages: 100,
      contents: '목차.',
      price: 20000,
      pub_date: '2222-02-02',
      likes: 1,
      liked: 0,
      category_id: 1,
      category_name: '소설',
    },
  ],
  bookDetailResData: {
    id: 2,
    title: '책',
    img: 5,
    form: '종이책',
    isbn: 5,
    summary: '요약',
    detail: '디테일',
    author: '작가',
    pages: 100,
    contents: '목차.',
    price: 20000,
    pub_date: '2222-02-02',
    likes: 1,
    liked: 0,
    categoryId: 1,
    categoryName: '소설',
  },
};

export default ServiceMockData;
