
name: build-deploy

on:
  push:
    branches: ['main']
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: evanskj/book-shop:latest

      - name: Generate Dockerhub Ebextension auth config
        run: |
          export DOCKER_AUTH=$(echo -n "${{ secrets.DOCKERHUB_USER }}:${{ secrets.DOCKERHUB_PASSWORD }}" | base64)
          envsubst < .ebextensions/dockerhub_auth.config.template > .ebextensions/dockerhub_auth.config

      - name: Generate deploy package
        run: |
          zip -r deploy.zip docker-compose.yaml .ebextensions

      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          application_name: ${{ secrets.AWS_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_ENVIRONMENT_NAME }}
          version_label: '${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}'
          region: ap-northeast-2
          deployment_package: deploy.zip
